# Generated by Django 4.2.25 on 2025-10-21 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_rubric_strictness_rubric_subject_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
