# Generated by Django 4.2.25 on 2025-10-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_student_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='grade_level',
            field=models.CharField(default='Grade 1', max_length=50),
        ),
    ]
