# Generated by Django 4.2.25 on 2025-10-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_progress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='training_data',
            field=models.JSONField(null=True),
        ),
    ]
