# Generated by Django 4.2.25 on 2025-10-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rubric_training_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='evaluate',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
